/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vn.fpt.edu.view;

/**
 *
 * @author Le Huy
 */
public class FormTaiKhoan extends javax.swing.JFrame {

    /**
     * Creates new form FormTaiKhoan
     */
    public FormTaiKhoan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblID = new javax.swing.JLabel();
        lblHoten = new javax.swing.JLabel();
        lblDiaChi = new javax.swing.JLabel();
        lblNamsinh = new javax.swing.JLabel();
        lblGmail = new javax.swing.JLabel();
        lblSDT = new javax.swing.JLabel();
        lblChucvu = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtHoten = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtNamsinh = new javax.swing.JTextField();
        txtGmail = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        btnDoimatkhau = new javax.swing.JButton();
        btnDangxuat = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblID.setText("ID:");

        lblHoten.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHoten.setText("Họ Tên:");

        lblDiaChi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDiaChi.setText("Địa Chỉ:");

        lblNamsinh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNamsinh.setText("Năm Sinh:");

        lblGmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblGmail.setText("Gmail:");

        lblSDT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSDT.setText("SĐT:");

        lblChucvu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblChucvu.setText("Chức Vụ:");

        txtID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtHoten.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtDiaChi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtNamsinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNamsinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamsinhActionPerformed(evt);
            }
        });

        txtGmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtSDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnDoimatkhau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDoimatkhau.setText("Đổi Mật Khẩu");
        btnDoimatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoimatkhauActionPerformed(evt);
            }
        });

        btnDangxuat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDangxuat.setText("Đăng Xuất");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nhân viên", "quản lý" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(322, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDoimatkhau)
                        .addGap(45, 45, 45)
                        .addComponent(btnDangxuat))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblID)
                            .addComponent(lblHoten)
                            .addComponent(lblDiaChi)
                            .addComponent(lblNamsinh)
                            .addComponent(lblGmail)
                            .addComponent(lblSDT)
                            .addComponent(lblChucvu))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(txtHoten)
                            .addComponent(txtDiaChi)
                            .addComponent(txtNamsinh)
                            .addComponent(txtGmail)
                            .addComponent(txtSDT)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(312, 312, 312))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblHoten, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblDiaChi)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblNamsinh)
                    .addComponent(txtNamsinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblGmail)
                    .addComponent(txtGmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblSDT)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblChucvu)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDoimatkhau)
                    .addComponent(btnDangxuat))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamsinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamsinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamsinhActionPerformed

    private void btnDoimatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoimatkhauActionPerformed
        FormDoiMatKhau t = new FormDoiMatKhau();
        t.setVisible(true);
        t.setSize(400, 300);
        t.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnDoimatkhauActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangxuat;
    private javax.swing.JButton btnDoimatkhau;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lblChucvu;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblGmail;
    private javax.swing.JLabel lblHoten;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNamsinh;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtGmail;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNamsinh;
    private javax.swing.JTextField txtSDT;
    // End of variables declaration//GEN-END:variables
}
