/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vn.fpt.edu.view;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.*;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Random;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import vn.fpt.edu.connect.Connect;

/**
 *
 * @author Le Huy
 */
public class FormKhoHang extends javax.swing.JFrame {

    JTable table = new JTable();
    Connect kn = new Connect();
    Connection cn = kn.getConnect();
    PreparedStatement stm = null;
    Statement st = null;
    ResultSet rs = null;
    DefaultTableModel dftb = new DefaultTableModel();
    int maHd;

    /**
     * Creates new form FormKhoHang
     */
    public FormKhoHang() {
        initComponents();
        getdata();
       
    }

    public void getdata() {

        Vector data = new Vector();
        Vector header = new Vector();
        header.add("STT");
        header.add("Mã HH");
        header.add("Tên HH");
        header.add("Đơn vị");
        header.add("Nhà sản xuất");
        header.add("Ngày sản xuất");
        header.add("Hạn sử dụng");
        header.add("Số lượng");
        header.add("Giá tiền");
        
        table.setPreferredScrollableViewportSize(new Dimension(1000, 230));

        String sql = "Select * FROM HANGHOA";
        try {
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            int i = 1;
            while (rs.next()) {
                Vector data1 = new Vector();

                data1.add(i);
                data1.add(rs.getString(1));
                data1.add(rs.getString(2));
                data1.add(rs.getString(3));
                data1.add(rs.getString(4));
                data1.add(rs.getString(5));
                data1.add(rs.getString(6));
                data1.add(rs.getString(7));
                data1.add(rs.getString(8));
               
                data.add(data1);
                table.setModel(new DefaultTableModel(data, header));
                i++;

            }

        } catch (Exception e) {
        }
        table.setModel(new DefaultTableModel(data, header));

        jScrollPane1.setViewportView(table);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlTop = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();
        txtTim = new javax.swing.JTextField();
        pnlBottom = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kho hàng");

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        txtTim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(124, 124, 124)
                .addComponent(txtTim, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBottom.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                pnlBottomAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout pnlBottomLayout = new javax.swing.GroupLayout(pnlBottom);
        pnlBottom.setLayout(pnlBottomLayout);
        pnlBottomLayout.setHorizontalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        pnlBottomLayout.setVerticalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBottom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int row = table.getSelectedRow();
        String mahang = (String) table.getValueAt(row, 1);
        String sql = "update hanghoa set tenhanghoa=?,donvi=?,trongluong=?,nsx=?,nhasanxuat=?,hansudung=?,soluong=?,gia=? where mahanghoa=?";
        try {

            stm = cn.prepareStatement(sql);
            rs = stm.executeQuery();
            Vector data = new Vector();
            Vector header = new Vector();
            header.add("STT");
            header.add("Mã HH");
            header.add("Tên HH");
            header.add("Đơn vị");
            header.add("Trọng Lượng");
            header.add("Nhà sản xuất");
            header.add("Ngày sản xuất");
            header.add("Hạn sử dụng");
            header.add("Giá tiền");
            header.add("Số lượng");
            while (rs.next()) {
                int i = 1;
                Vector data1 = new Vector();

                data1.add(i);
                data1.add(rs.getString(1));
                data1.add(rs.getString(2));
                data1.add(rs.getString(3));
                data1.add(rs.getString(4));
                data1.add(rs.getString(5));
                data1.add(rs.getString(6));
                data1.add(rs.getString(7));
                data1.add(rs.getString(8));
                data1.add(rs.getString(9));
                data.add(data1);
                table.setModel(new DefaultTableModel(data, header));

            }
            stm.setString(1, sql);

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void txtTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimActionPerformed

    }//GEN-LAST:event_txtTimActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        FormNhapHang t = new FormNhapHang();
        t.setVisible(true);
        t.setSize(1000, 700);
        t.setLocationRelativeTo(null);
        close();
    }//GEN-LAST:event_btnThemActionPerformed
    public void close() {
        this.dispose();
    }
    private void pnlBottomAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_pnlBottomAncestorAdded

    }//GEN-LAST:event_pnlBottomAncestorAdded

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row = table.getSelectedRow();
        String mahang = (String) table.getValueAt(row, 1);
        String sql = "delete from hanghoa where mahanghoa=?";
        try {
            stm = cn.prepareStatement(sql);
            stm.setString(1, mahang);
            stm.executeUpdate();
            getdata();
            JOptionPane.showMessageDialog(null, "đã xóa");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "lỗi" + e);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        FormTimHang m = new FormTimHang();
        m.setVisible(true);
        m.setLocationRelativeTo(null);
        m.setSize(350, 370);


    }//GEN-LAST:event_btnTimActionPerformed
    public void Tim() {
        String sql = "select * form hanghoa where mahanghoa=?";
        try {
            stm = cn.prepareStatement(sql);
            stm.setString(1, txtTim.getText());

            Vector data = new Vector();
            Vector header = new Vector();
            header.add("STT");
            header.add("Mã HH");
            header.add("Tên HH");
            header.add("Đơn vị");
            header.add("Trọng Lượng");
            header.add("Nhà sản xuất");
            header.add("Ngày sản xuất");
            header.add("Hạn sử dụng");
            header.add("Giá tiền");
            header.add("Số lượng");
            while (rs.next()) {
                Vector data1 = new Vector();

                data1.add("1");
                data1.add(rs.getString(1));
                data1.add(rs.getString(2));
                data1.add(rs.getString(3));
                data1.add(rs.getString(4));
                data1.add(rs.getString(5));
                data1.add(rs.getString(6));
                data1.add(rs.getString(7));
                data1.add(rs.getString(8));
                data1.add(rs.getString(9));
                data.add(data1);
                table.setModel(new DefaultTableModel(data, header));
                JOptionPane.showMessageDialog(null, data);

            }
        } catch (SQLException ex) {
            Logger.getLogger(FormKhoHang.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void a() {
        JOptionPane.showMessageDialog(null, "a");
    }

    public void Timhang() {
        String tim = txtTim.getText();
        int counter = dftb.getRowCount();
        Vector data1 = new Vector();
        for (int i = 1; i <= counter; i++) {
            if (tim.equals(table.getValueAt(i, 1))) {
                Vector data = new Vector();
                data.add(table.getValueAt(i, 1));
                data.add(table.getValueAt(i, 1));
                data.add(table.getValueAt(i, 2));
                data.add(table.getValueAt(i, 3));
                data.add(table.getValueAt(i, 4));
                data.add(table.getValueAt(i, 5));
                data.add(table.getValueAt(i, 6));
                data.add(table.getValueAt(i, 7));
                data.add(table.getValueAt(i, 8));
                data.add(table.getValueAt(i, 9));
                data1.add(data);
                JOptionPane.showMessageDialog(null, data, tim, HEIGHT);
            }

        }
    }

    public String mahang() {
        return txtTim.getText();
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
}
