/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vn.fpt.edu.view;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import vn.fpt.edu.process.LuuKhiSua;
import vn.fpt.edu.process.*;

/**
 *
 * @author Admin
 */
public class FormSuaHang extends javax.swing.JFrame {

    /**
     * Creates new form FormSuaHang
     */
    public FormSuaHang() {
        initComponents();
        txtGia.setDocument(new DigitsDocument()); 
        txtSoluong.setDocument(new DigitsDocument()); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtma = new javax.swing.JTextField();
        txtSoluong = new javax.swing.JTextField();
        txtNhaSanxuat = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        cbbDv = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        txtMahang = new javax.swing.JLabel();
        txtMahang1 = new javax.swing.JLabel();
        txtMahang2 = new javax.swing.JLabel();
        txtMahang3 = new javax.swing.JLabel();
        txtMahang4 = new javax.swing.JLabel();
        txtMahang5 = new javax.swing.JLabel();
        txtMahang6 = new javax.swing.JLabel();
        txtTenHang = new javax.swing.JTextField();
        txtMahang7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtma.setEditable(false);
        txtma.setText("jTextField1");

        txtSoluong.setText("jTextField1");

        txtNhaSanxuat.setText("jTextField1");

        txtGia.setText("jTextField1");

        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnback.setText("Quay lại");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        cbbDv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kg", "Hộp", "Cái" }));
        cbbDv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbDvActionPerformed(evt);
            }
        });

        txtMahang.setText("Mã hàng");

        txtMahang1.setText("Loại");

        txtMahang2.setText("Ngày sản xuất");

        txtMahang3.setText("Hạn sử dụng");

        txtMahang4.setText("Số lượng");

        txtMahang5.setText("Giá");

        txtMahang6.setText("Nhà sản xuất");

        txtTenHang.setText("jTextField1");

        txtMahang7.setText("Tên hàng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSave)
                        .addGap(37, 37, 37)
                        .addComponent(btnback))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMahang)
                            .addComponent(txtMahang1)
                            .addComponent(txtMahang2)
                            .addComponent(txtMahang3)
                            .addComponent(txtMahang4)
                            .addComponent(txtMahang5)
                            .addComponent(txtMahang6)
                            .addComponent(txtMahang7))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSoluong, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(txtma)
                            .addComponent(txtNhaSanxuat, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtGia)
                            .addComponent(cbbDv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTenHang, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMahang7))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMahang))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbDv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMahang1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMahang2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNhaSanxuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMahang6))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMahang3))
                        .addGap(18, 18, 18)
                        .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtMahang4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMahang5))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnback))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        FormKhoHang m=new FormKhoHang();
        m.setTitle("Quản lý siêu thị mini");
        m.setSize(1000,700);
        m.setResizable(false);
        m.setLocationRelativeTo(null);
        m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        m.setVisible(true);
        close();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        LuuKhiSua lks=new LuuKhiSua();
        String donvi;
        if(cbbDv.getSelectedIndex()==0){
        donvi="kg";
        }
        if(cbbDv.getSelectedIndex()==1){
        donvi="Hộp";
        }
        else{donvi="cái";}
         DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
      
        String goidate = dateFormat.format(jDateChooser1.getDate());
        String goidate2 = dateFormat.format(jDateChooser2.getDate());
        int ma=Integer.parseInt(txtma.getText());
        lks.LuuKhiSua(ma, txtTenHang.getText(), donvi, goidate,txtNhaSanxuat.getText()
                , goidate2, Integer.parseInt(txtSoluong.getText()), Integer.parseInt(txtGia.getText()));
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cbbDvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbDvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbDvActionPerformed
public void close(){
this.dispose();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSuaHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSuaHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSuaHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSuaHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSuaHang().setVisible(true);
            }
        });
    }
public void data(int mahanghoa, String tenhanghoa, String donvi, String nsx,
        String nhasanxuat, String hansudung, int soluong, int gia) throws ParseException {
txtma.setText(mahanghoa+"");
txtSoluong.setText(soluong+"");
if(donvi.equalsIgnoreCase("Kg")){
cbbDv.setSelectedIndex(0);
}
if(donvi.equalsIgnoreCase("Hộp")){
cbbDv.setSelectedIndex(1);
}
else{
cbbDv.setSelectedIndex(2);
}
Date date = new SimpleDateFormat("yyyy-mm-dd").parse(nsx);
Date date1 = new SimpleDateFormat("yyyy-mm-dd").parse(hansudung);
jDateChooser1.setDate(date);
jDateChooser2.setDate(date1);
txtNhaSanxuat.setText(nhasanxuat);

txtGia.setText(gia+"");
txtTenHang.setText(tenhanghoa);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnback;
    private javax.swing.JComboBox<String> cbbDv;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JTextField txtGia;
    private javax.swing.JLabel txtMahang;
    private javax.swing.JLabel txtMahang1;
    private javax.swing.JLabel txtMahang2;
    private javax.swing.JLabel txtMahang3;
    private javax.swing.JLabel txtMahang4;
    private javax.swing.JLabel txtMahang5;
    private javax.swing.JLabel txtMahang6;
    private javax.swing.JLabel txtMahang7;
    private javax.swing.JTextField txtNhaSanxuat;
    private javax.swing.JTextField txtSoluong;
    private javax.swing.JTextField txtTenHang;
    private javax.swing.JTextField txtma;
    // End of variables declaration//GEN-END:variables
}
