/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vn.fpt.edu.view;

import javax.swing.JFrame;
import vn.fpt.edu.process.LayduLieuNhanVien;

/**
 *
 * @author Le Huy
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltk = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        QuanLy = new javax.swing.JCheckBoxMenuItem();
        TaiKhoan = new javax.swing.JCheckBoxMenuItem();
        openMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        functionMenu = new javax.swing.JMenu();
        banhang = new javax.swing.JMenuItem();
        khohang = new javax.swing.JMenuItem();
        baocao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý bán hàng siêu thị mini");

        lbltk.setText("jLabel1");

        file.setMnemonic('f');
        file.setText("tài khoản");
        file.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        QuanLy.setSelected(true);
        QuanLy.setText("Quản lý");
        QuanLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuanLyActionPerformed(evt);
            }
        });
        file.add(QuanLy);

        TaiKhoan.setSelected(true);
        TaiKhoan.setText("Tài khoản");
        TaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaiKhoanActionPerformed(evt);
            }
        });
        file.add(TaiKhoan);

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Đăng xuất");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        file.add(openMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Thoát");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        file.add(exitMenuItem);

        menuBar.add(file);

        functionMenu.setMnemonic('e');
        functionMenu.setText("làm việc");
        functionMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        banhang.setMnemonic('t');
        banhang.setText("Bán hàng");
        banhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banhangActionPerformed(evt);
            }
        });
        functionMenu.add(banhang);

        khohang.setMnemonic('y');
        khohang.setText("Kho hàng");
        khohang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                khohangActionPerformed(evt);
            }
        });
        functionMenu.add(khohang);

        baocao.setMnemonic('d');
        baocao.setText("Báo Cáo");
        baocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baocaoActionPerformed(evt);
            }
        });
        functionMenu.add(baocao);

        menuBar.add(functionMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(lbltk)
                .addContainerGap(554, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(lbltk)
                .addContainerGap(329, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QuanLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuanLyActionPerformed
        FormQuanLy t = new FormQuanLy() {
        };

        t.setVisible(true);
        t.setSize(900, 500);
        t.setLocationRelativeTo(null);
    }//GEN-LAST:event_QuanLyActionPerformed

    private void TaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaiKhoanActionPerformed
       
        FormTaiKhoan t = new FormTaiKhoan();
        FormDangNhap m=new FormDangNhap();
      lbltk.setText(m.getTaikhoan());
        t.setVisible(true);
        t.setSize(900, 500);
        t.setLocationRelativeTo(null);
    }//GEN-LAST:event_TaiKhoanActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void banhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banhangActionPerformed
        FormBanHang t = new FormBanHang();
        t.setVisible(true);
        t.setSize(1000, 800);
        t.setLocationRelativeTo(null);
    }//GEN-LAST:event_banhangActionPerformed

    private void khohangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_khohangActionPerformed
        FormKhoHang t = new FormKhoHang();
        t.setVisible(true);
        t.setSize(900, 500);
        t.setLocationRelativeTo(null);
    }//GEN-LAST:event_khohangActionPerformed

    private void baocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baocaoActionPerformed
        FormBaoCao t = new FormBaoCao();
        t.setVisible(true);
        t.setSize(900, 500);
        t.setLocationRelativeTo(null);
    }//GEN-LAST:event_baocaoActionPerformed
    public void tk(String tk) {
       
        //FormDangNhap dn = new FormDangNhap();
        //tk = dn.getTaikhoan();
        LayduLieuNhanVien dlnv = new LayduLieuNhanVien();
        System.out.println(tk + "tk");
        FormTaiKhoan ftk = new FormTaiKhoan();
        ftk.getTt(tk, dlnv.getmauserr(tk), dlnv.gettenn(tk), dlnv.getngaysinhh(tk), dlnv.getemaill(tk), dlnv.getsdtt(tk), dlnv.getchucvuu(tk));
    }
  /**
     * @param args the command line arguments
     *
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Menu m = new Menu();
        m.setTitle("Quản lý siêu thị mini");
        m.setSize(1000, 700);
        m.setResizable(false);
        m.setLocationRelativeTo(null);
        m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        m.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem QuanLy;
    private javax.swing.JCheckBoxMenuItem TaiKhoan;
    private javax.swing.JMenuItem banhang;
    private javax.swing.JMenuItem baocao;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu file;
    private javax.swing.JMenu functionMenu;
    private javax.swing.JMenuItem khohang;
    private javax.swing.JLabel lbltk;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    // End of variables declaration//GEN-END:variables
}
